CREATE TABLE DEPARTMENT (
 DEPARTMENT_CD CHAR(5) NOT NULL PRIMARY KEY
,DEPARTMENT_NAME VARCHAR(20) NOT NULL
,ADD_DATE DATETIME NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATETIME
,UPDATE_USER VARCHAR(20)
)
