CREATE TABLE DEPARTMENT (
 DEPARTMENT_CD CHAR(5) NOT NULL PRIMARY KEY
,DEPARTMENT_NAME VARCHAR(20) NOT NULL
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
)
