CREATE TABLE ERR_LOG(
    ID INT AUTO_INCREMENT PRIMARY KEY
    ,PROC_NAME VARCHAR(30) NOT NULL -- プロシージャ名
    ,ERR_CODE CHAR(5) NOT NULL       -- SQLSTATE
    ,ERR_MESSAGE TEXT               -- エラー詳細内容
    ,ERR_PARAM TEXT                 -- 引数の値
    ,ADD_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
)