CREATE TABLE PASSWORD (
 USER_ID VARCHAR(20) NOT NULL PRIMARY KEY
,PASSWORD_HASH VARCHAR(255) NOT NULL
,QUESTION TINYTEXT NOT NULL
,ANSWER TINYTEXT NOT NULL
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)