CREATE TABLE PERSONAL_GOALS(
USER_ID VARCHAR(20) NOT NULL
,YEARMONTH VARCHAR(6) NOT NULL
,PERIODS TINYINT(1) NOT NULL
,GOAL TEXT NOT NULL
,RESULT TEXT
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (USER_ID, YEARMONTH, PERIODS)
,FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)