CREATE TABLE PRIVATE_ASSIGNMENT(
USER_ID VARCHAR(20) NOT NULL
,YEARMONTH VARCHAR(6) NOT NULL
,OCCUR_DATE DATE NOT NULL
,ASSIGNMENT TEXT
,CORRESPONDENCE TEXT
,COMP_DATE DATE
,SITUATION VARCHAR(20)
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (USER_ID, YEARMONTH, OCCUR_DATE)
,FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)