CREATE TABLE REPORT(
USER_ID VARCHAR(20) NOT NULL
,YEARMONTH VARCHAR(6) NOT NULL
,WEEK_NO TINYINT(1) NOT NULL
,DO TEXT
,CHECKS TEXT
,ACTIONS TEXT
,PLAN TEXT
,REPORT TEXT
,COMMENTUSERID VARCHAR(20)
,COMMENT TEXT
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (USER_ID, YEARMONTH, WEEK_NO)
,FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
,FOREIGN KEY (COMMENTUSERID) REFERENCES USER(USER_ID)
)