CREATE TABLE REVIEW (
ASSESSOR_ID VARCHAR(20) NOT NULL
,ADD_DATE DATE NOT NULL
,EVALUATER_ID VARCHAR(20) NOT NULL
,GENERAL_REVIEW TEXT
,ESCALATION TEXT
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (ASSESSOR_ID, ADD_DATE, EVALUATER_ID)
,FOREIGN KEY (ASSESSOR_ID) REFERENCES USER(USER_ID)
,FOREIGN KEY (EVALUATER_ID) REFERENCES USER(USER_ID)
)