CREATE TABLE REVIEW (
ASSESSOR_ID VARCHAR(20) NOT NULL
,ADD_DATE DATETIME NOT NULL
,EVALUATER_ID VARCHAR(20) NOT NULL
,GENERAL_REVIEW TEXT
,ESCALATION TEXT
,UPDATE_DATE DATETIME
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (ASSESSOR_ID, ADD_DATE, EVALUATER_ID)
)