CREATE TABLE TASK_COUNT (
USER_ID VARCHAR(20) NOT NULL
,YEARMONTH VARCHAR(6) NOT NULL
,WEEK TINYINT(1) NOT NULL
,OCCUR_NUMBER INT
,INPRO_NUMBER INT
,COMP_NUMBER INT
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (USER_ID, YEARMONTH, WEEK)
,FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
)
