CREATE TABLE USER (
 USER_ID VARCHAR(20) NOT NULL PRIMARY KEY
,USER_LN VARCHAR(50) NOT NULL
,USER_FN VARCHAR(50) NOT NULL
,USER_MN VARCHAR(50)
,LEADER_FG TINYINT(1) NOT NULL
,ENABLED_FG TINYINT(1) NOT NULL
,DEPARTMENT_CD CHAR(5) NOT NULL
,ADD_DATE DATE NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATE
,UPDATE_USER VARCHAR(20)
,FOREIGN KEY (DEPARTMENT_CD) REFERENCES DEPARTMENT(DEPARTMENT_CD)
)