CREATE TABLE WORKING_TIME (
 USER_ID VARCHAR(20) NOT NULL
,YEARMONTH VARCHAR(6) NOT NULL
,WEEK TINYINT(1) NOT NULL
,EXPECTATION FLOAT(4)
,RESULT FLOAT(4)
,ADD_DATE DATETIME NOT NULL
,ADD_USER VARCHAR(20) NOT NULL
,UPDATE_DATE DATETIME
,UPDATE_USER VARCHAR(20)
,PRIMARY KEY (USER_ID, YEARMONTH, WEEK)
)
